# Generated by Django 2.2.12 on 2020-06-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('begin_date', models.CharField(max_length=4)),
                ('end_date', models.CharField(max_length=7)),
            ],
        ),
    ]
